SELECT RESPIRADORES.DESTINO, 
Quantidade = SUM(RESPIRADORES.QUANTIDADE) , 
Valor = SUM(RESPIRADORES.VALOR)
FROM TB_Respiradores AS RESPIRADORES
GROUP BY RESPIRADORES.DESTINO 
ORDER BY  Quantidade

SELECT FORNECEDOR, SUM(QUANTIDADE) AS QUANTIDADE,SUM(VALOR)
FROM TB_Respiradores
GROUP BY FORNECEDOR
order BY QUANTIDADE DESC